// Copyright 2025-2026 mrveiss
// SPDX-License-Identifier: Apache-2.0
/**
 * The storable secret kinds, taken from the generated API types (#15008).
 *
 * `SecretCreateRequest.type` is emitted from the canonical `SecretType` enum
 * (autobot_shared/status_enums.py) and regenerated by CI, so a kind added on
 * the backend reaches the frontend with no second, hand-kept edit.
 */
import type { components } from '@/types/generated/api'

export type SecretType = components['schemas']['SecretCreateRequest']['type']
