#!/usr/bin/env python3
"""Pre-commit hook: verify all AUTOBOT_* os.getenv() calls are registered.

Also checks that the autogenerated section of docs/developer/CLAUDE_RULES.md
is up to date with the current registry.

Usage (pre-commit passes staged file paths as argv):

    python3 pipeline-scripts/check_env_var_registry.py <file1.py> [<file2.py> ...]

Exits 0 on success, 1 on any violation.

Closes GH#7081.
"""

import ast
import sys
from pathlib import Path

# ---------------------------------------------------------------------------
# Bootstrap path so the registry module is importable from the repo root.
# ---------------------------------------------------------------------------
REPO_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO_ROOT))

from autobot_shared.env_registry import REGISTRY  # noqa: E402

DOCS_PATH = REPO_ROOT / "docs" / "developer" / "CLAUDE_RULES.md"

BEGIN_MARKER = "<!-- BEGIN_AUTOGEN_ENV_DOCS -->"
END_MARKER = "<!-- END_AUTOGEN_ENV_DOCS -->"

# Files that define the registry itself — skip them to avoid false positives.
REGISTRY_PATHS = {
    "autobot_shared/env_registry.py",
}


def _is_registry_file(path: Path) -> bool:
    normalized = str(path).replace("\\", "/")
    return any(rp in normalized for rp in REGISTRY_PATHS)


# ---------------------------------------------------------------------------
# AST scanning
# ---------------------------------------------------------------------------


def _extract_autobot_getenv_names(path: Path) -> list[tuple[int, str]]:
    """Return (lineno, var_name) pairs for os.getenv("AUTOBOT_*") calls in *path*."""
    try:
        source = path.read_text(encoding="utf-8")
    except (OSError, UnicodeDecodeError):
        return []

    try:
        tree = ast.parse(source, filename=str(path))
    except SyntaxError:
        return []

    results: list[tuple[int, str]] = []

    for node in ast.walk(tree):
        if not isinstance(node, ast.Call):
            continue

        func = node.func

        # Match os.getenv("AUTOBOT_...") and getenv("AUTOBOT_...")
        is_getenv = (isinstance(func, ast.Attribute) and func.attr == "getenv") or (
            isinstance(func, ast.Name) and func.id == "getenv"
        )

        if not is_getenv:
            continue

        if not node.args:
            continue

        first_arg = node.args[0]
        if not isinstance(first_arg, ast.Constant):
            continue
        if not isinstance(first_arg.value, str):
            continue
        if not first_arg.value.startswith("AUTOBOT_"):
            continue

        results.append((node.lineno, first_arg.value))

    return results


# ---------------------------------------------------------------------------
# Docs freshness check (inline — no subprocess, no extra dependencies)
# ---------------------------------------------------------------------------


def _build_table(registry: dict) -> str:
    """Build the Markdown table string for the autogenerated section."""
    rows = []
    for name in sorted(registry):
        spec = registry[name]
        desc = spec.description.replace("|", "\\|")
        if spec.range is not None:
            lo, hi = spec.range
            desc += f" Range: {lo}–{hi}."
        if spec.default is None:
            default_str = "*(none)*"
        elif spec.type is bool:
            default_str = str(spec.default).lower()
        elif spec.type is str and spec.default == "":
            default_str = '`""`'
        else:
            default_str = f"`{spec.default!r}`"
        row = f"| `{name}` | {spec.component} | {spec.type.__name__} " f"| {default_str} | {desc} |"
        rows.append(row)

    header = "| Name | Component | Type | Default | Description |\n" "|---|---|---|---|---|"
    table_body = "\n".join(rows)
    count_note = f"\n\n*{len(registry)} variables registered as of last generation.*\n"
    return f"{header}\n{table_body}{count_note}"


def _extract_autogen_section(text: str) -> str:
    """Return the content between the magic markers (exclusive)."""
    begin_idx = text.find(BEGIN_MARKER)
    end_idx = text.find(END_MARKER)
    if begin_idx == -1 or end_idx == -1 or begin_idx >= end_idx:
        return ""
    return text[begin_idx + len(BEGIN_MARKER) : end_idx]


def check_docs_freshness() -> list[str]:
    """Return violation messages if the autogenerated section is stale."""
    violations: list[str] = []

    if not DOCS_PATH.exists():
        violations.append(f"docs: {DOCS_PATH} not found")
        return violations

    current_text = DOCS_PATH.read_text(encoding="utf-8")
    current_section = _extract_autogen_section(current_text)

    if not current_section:
        violations.append(
            f"docs: magic markers missing in {DOCS_PATH}. " "Run: python3 pipeline-scripts/generate_env_docs.py"
        )
        return violations

    # Build the expected section in memory using the live registry.
    expected_section = "\n" + _build_table(REGISTRY)

    if current_section != expected_section:
        violations.append(
            f"{DOCS_PATH}: autogenerated env-var table is stale.\n"
            "  Run:  python3 pipeline-scripts/generate_env_docs.py\n"
            "  Then: git add docs/developer/CLAUDE_RULES.md"
        )

    return violations


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------


def main(argv: list[str]) -> int:
    registry_violations: list[str] = []
    docs_violations: list[str] = []

    # 1. Check every passed Python file for unregistered AUTOBOT_* vars.
    for arg in argv:
        path = Path(arg)
        if path.suffix != ".py":
            continue
        if _is_registry_file(path):
            continue

        for lineno, var_name in _extract_autobot_getenv_names(path):
            if var_name not in REGISTRY:
                registry_violations.append(
                    f"{path}:{lineno}: unregistered env var '{var_name}'\n"
                    f"  Add it to autobot_shared/env_registry.py before use."
                )

    # 2. Check docs freshness only when Python files were actually inspected
    #    (avoids spurious failures when hook runs on non-Python staged sets).
    py_files_checked = any(Path(a).suffix == ".py" for a in argv)
    if py_files_checked:
        docs_violations = check_docs_freshness()

    all_violations = registry_violations + docs_violations

    if all_violations:
        print(
            "env-vars-documented: AUTOBOT_* env var violations found:\n",
            file=sys.stderr,
        )
        for v in all_violations:
            print(f"  {v}", file=sys.stderr)
        print(
            "\nFix:\n"
            "  1. Register the variable in autobot_shared/env_registry.py\n"
            "  2. Run: python3 pipeline-scripts/generate_env_docs.py\n"
            "  3. Stage the updated CLAUDE_RULES.md with: git add docs/developer/CLAUDE_RULES.md",
            file=sys.stderr,
        )
        return 1

    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
