#!/usr/bin/env python3
# Copyright 2025-2026 mrveiss
# SPDX-License-Identifier: Apache-2.0
"""Pre-commit hook: verify all AUTOBOT_* os.getenv() calls are registered.

Also checks that the autogenerated section of docs/developer/CLAUDE_RULES.md
is up to date with the current registry.

Usage (pre-commit passes staged file paths as argv):

    python3 pipeline-scripts/check_env_var_registry.py <file1.py> [<file2.py> ...]

Exits 0 on success, 1 on any violation.

Closes GH#7081.
"""

import ast
import functools
import sys
from pathlib import Path

# ---------------------------------------------------------------------------
# Bootstrap path so the registry module is importable from the repo root.
# ---------------------------------------------------------------------------
REPO_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO_ROOT))

from autobot_shared.env_registry import REGISTRY  # noqa: E402

DOCS_PATH = REPO_ROOT / "docs" / "developer" / "CLAUDE_RULES.md"

BEGIN_MARKER = "<!-- BEGIN_AUTOGEN_ENV_DOCS -->"
END_MARKER = "<!-- END_AUTOGEN_ENV_DOCS -->"

# Files that define the registry itself — skip them to avoid false positives.
REGISTRY_PATHS = {
    "autobot_shared/env_registry.py",
    # Per-component split (#15624). `env_registry.py` was exactly at its size
    # ceiling, so no new variable could be registered anywhere. Each of these
    # defines registry entries and must be skipped for the same reason the
    # parent is: its `name=` strings are declarations, not usages.
    "autobot_shared/env_registry_backend.py",
}


def _is_registry_file(path: Path) -> bool:
    normalized = str(path).replace("\\", "/")
    return any(rp in normalized for rp in REGISTRY_PATHS)


# ---------------------------------------------------------------------------
# AST scanning
# ---------------------------------------------------------------------------


_ENV_UTILS = REPO_ROOT / "autobot_shared" / "env_utils.py"


@functools.lru_cache(maxsize=1)
def _env_reader_names() -> frozenset[str]:
    """Every helper in ``autobot_shared/env_utils.py`` that reads a named variable.

    Derived from that module rather than hard-coded (#14265). The checker used to
    match ``os.getenv`` alone, so every variable read through ``env_int`` /
    ``env_flag`` / ``env_str`` / ``env_float`` was invisible to it -- 52 of them.
    Those helpers are not an alternative mechanism; they wrap the same read with
    the blank-is-absent guard from #12782, and are the form this repo prefers. A
    checker that sees only the discouraged spelling reports clean and reads as
    coverage.

    Deriving the set means a helper added later is covered without anyone
    remembering to extend a list here -- which is the failure this issue is.
    """
    source = _ENV_UTILS.read_text(encoding="utf-8")
    tree = ast.parse(source, filename=str(_ENV_UTILS))
    readers = {
        node.name
        for node in tree.body
        if isinstance(node, ast.FunctionDef)
        and node.name.startswith("env_")
        and node.args.args
        and node.args.args[0].arg == "name"
    }
    if not readers:
        # An empty set silently disables half the check. That is the exact shape
        # of the bug this function exists to fix.
        sys.exit(f"FATAL: no env-reading helpers found in {_ENV_UTILS} — refusing to check half the tree")
    return frozenset(readers)


def _self_provided_names(tree: ast.AST) -> set[str]:
    """Names this file sets for itself before reading them (#14265).

    `env_utils_blank_test.py` does `monkeypatch.setenv("AUTOBOT_TEST_BLANK", …)`
    and reads it straight back to prove blank-is-absent. That is a fixture, not
    deployed configuration, and registering it would put a variable in the
    documented environment that no deployment ever sets.

    Expressed as a rule rather than an allowlist entry: a name the file supplies
    itself is not evidence of an unregistered setting. A genuinely deployed
    variable that a test also monkeypatches is still caught, because production
    code reads it somewhere this exemption does not apply.
    """
    provided: set[str] = set()
    for node in ast.walk(tree):
        if isinstance(node, ast.Call):
            func = node.func
            name = func.attr if isinstance(func, ast.Attribute) else getattr(func, "id", None)
            if name in {"setenv", "setdefault"} and node.args:
                first = node.args[0]
                if isinstance(first, ast.Constant) and isinstance(first.value, str):
                    provided.add(first.value)
        elif isinstance(node, ast.Subscript) and isinstance(node.slice, ast.Constant):
            value = node.slice.value
            if isinstance(value, str):
                provided.add(value)
    return provided


def _extract_autobot_getenv_names(path: Path) -> list[tuple[int, str]]:
    """Return (lineno, var_name) pairs for every AUTOBOT_* env read in *path*.

    Covers ``os.getenv``/``getenv`` and the ``env_utils`` helpers alike.
    """
    try:
        source = path.read_text(encoding="utf-8")
    except (OSError, UnicodeDecodeError):
        return []

    try:
        tree = ast.parse(source, filename=str(path))
    except SyntaxError:
        return []

    results: list[tuple[int, str]] = []
    self_provided = _self_provided_names(tree)
    readers = _env_reader_names()

    for node in ast.walk(tree):
        if not isinstance(node, ast.Call):
            continue

        func = node.func

        # os.getenv("AUTOBOT_...") / getenv("AUTOBOT_...") and the env_utils
        # helpers, all of which take the variable name as their first argument.
        name = func.attr if isinstance(func, ast.Attribute) else getattr(func, "id", None)
        if name != "getenv" and name not in readers:
            continue

        if not node.args:
            continue

        first_arg = node.args[0]
        if not isinstance(first_arg, ast.Constant):
            continue
        if not isinstance(first_arg.value, str):
            continue
        if not first_arg.value.startswith("AUTOBOT_"):
            continue

        if first_arg.value in self_provided:
            continue

        results.append((node.lineno, first_arg.value))

    return results


# ---------------------------------------------------------------------------
# Docs freshness check (inline — no subprocess, no extra dependencies)
# ---------------------------------------------------------------------------


def _build_table(registry: dict) -> str:
    """Build the Markdown table string for the autogenerated section."""
    rows = []
    for name in sorted(registry):
        spec = registry[name]
        desc = spec.description.replace("|", "\\|")
        if spec.range is not None:
            lo, hi = spec.range
            desc += f" Range: {lo}–{hi}."
        if spec.default is None:
            default_str = "*(none)*"
        elif spec.type is bool:
            default_str = str(spec.default).lower()
        elif spec.type is str and spec.default == "":
            default_str = '`""`'
        else:
            default_str = f"`{spec.default!r}`"
        row = f"| `{name}` | {spec.component} | {spec.type.__name__} " f"| {default_str} | {desc} |"
        rows.append(row)

    header = "| Name | Component | Type | Default | Description |\n" "|---|---|---|---|---|"
    table_body = "\n".join(rows)
    count_note = f"\n\n*{len(registry)} variables registered as of last generation.*\n"
    return f"{header}\n{table_body}{count_note}"


def _extract_autogen_section(text: str) -> str:
    """Return the content between the magic markers (exclusive)."""
    begin_idx = text.find(BEGIN_MARKER)
    end_idx = text.find(END_MARKER)
    if begin_idx == -1 or end_idx == -1 or begin_idx >= end_idx:
        return ""
    return text[begin_idx + len(BEGIN_MARKER) : end_idx]


def check_docs_freshness() -> list[str]:
    """Return violation messages if the autogenerated section is stale."""
    violations: list[str] = []

    if not DOCS_PATH.exists():
        violations.append(f"docs: {DOCS_PATH} not found")
        return violations

    current_text = DOCS_PATH.read_text(encoding="utf-8")
    current_section = _extract_autogen_section(current_text)

    if not current_section:
        violations.append(
            f"docs: magic markers missing in {DOCS_PATH}. " "Run: python3 pipeline-scripts/generate_env_docs.py"
        )
        return violations

    # Build the expected section in memory using the live registry.
    expected_section = "\n" + _build_table(REGISTRY)

    if current_section != expected_section:
        violations.append(
            f"{DOCS_PATH}: autogenerated env-var table is stale.\n"
            "  Run:  python3 pipeline-scripts/generate_env_docs.py\n"
            "  Then: git add docs/developer/CLAUDE_RULES.md"
        )

    return violations


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------


# #14265: this held the 45 variables the checker could not see until it learned
# the env_utils helper form. All of them are now registered, and the two that
# were test fixtures are exempt by rule rather than by listing, so the set is
# EMPTY — which is the state it was always meant to reach.
#
# Kept rather than deleted: `_stale_baseline_entries` still runs against it, so
# the next time someone needs a temporary exemption there is a ceiling with a
# shrink check already attached, instead of a fresh list with neither.
_UNREGISTERED_BASELINE: frozenset[str] = frozenset()


def _stale_baseline_entries() -> list[str]:
    """Report any baselined name that has since been registered.

    Compared against the REGISTRY, not against the variables this invocation
    happened to scan: the hook usually runs on a handful of staged files, so
    "not seen this run" says nothing about whether a name is still unregistered.
    An earlier version of this function made that mistake and would have reported
    ~43 false violations on any normal pre-commit run.

    A name left here after being registered exempts whatever arrives under that
    name next, silently — the stranded-allowlist failure (#14236). Reported as a
    violation rather than quietly filtered, so the list is forced to shrink.
    """
    return [
        f"{name} is in _UNREGISTERED_BASELINE but is registered now — "
        f"remove it from pipeline-scripts/check_env_var_registry.py (#14265)"
        for name in sorted(_UNREGISTERED_BASELINE & set(REGISTRY))
    ]


def main(argv: list[str]) -> int:
    registry_violations: list[str] = _stale_baseline_entries()
    docs_violations: list[str] = []

    # 1. Check every passed Python file for unregistered AUTOBOT_* vars.
    for arg in argv:
        path = Path(arg)
        if path.suffix != ".py":
            continue
        if _is_registry_file(path):
            continue

        for lineno, var_name in _extract_autobot_getenv_names(path):
            if var_name not in REGISTRY:
                if var_name in _UNREGISTERED_BASELINE:
                    continue
                registry_violations.append(
                    f"{path}:{lineno}: unregistered env var '{var_name}'\n"
                    f"  Add it to autobot_shared/env_registry.py before use."
                )

    # 2. Check docs freshness only when Python files were actually inspected
    #    (avoids spurious failures when hook runs on non-Python staged sets).
    py_files_checked = any(Path(a).suffix == ".py" for a in argv)
    if py_files_checked:
        docs_violations = check_docs_freshness()

    all_violations = registry_violations + docs_violations

    if all_violations:
        print(
            "env-vars-documented: AUTOBOT_* env var violations found:\n",
            file=sys.stderr,
        )
        for v in all_violations:
            print(f"  {v}", file=sys.stderr)
        print(
            "\nFix:\n"
            "  1. Register the variable in autobot_shared/env_registry.py\n"
            "  2. Run: python3 pipeline-scripts/generate_env_docs.py\n"
            "  3. Stage the updated CLAUDE_RULES.md with: git add docs/developer/CLAUDE_RULES.md",
            file=sys.stderr,
        )
        return 1

    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
