#!/usr/bin/env python3
"""Generate the AUTOBOT_* env-var reference table in docs/developer/CLAUDE_RULES.md.

Reads the registry from autobot_shared/env_registry.py, builds a sorted
Markdown table, and rewrites the section bounded by:

    <!-- BEGIN_AUTOGEN_ENV_DOCS -->
    <!-- END_AUTOGEN_ENV_DOCS -->

Run from the repository root:

    python3 pipeline-scripts/generate_env_docs.py

Exits 0 on success, 1 on error.
"""

import sys
from pathlib import Path

# ---------------------------------------------------------------------------
# Bootstrap: allow running from repo root without installing the package.
# ---------------------------------------------------------------------------
REPO_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO_ROOT))

from autobot_shared.env_registry import REGISTRY, EnvVarSpec  # noqa: E402

DOCS_PATH = REPO_ROOT / "docs" / "developer" / "CLAUDE_RULES.md"

BEGIN_MARKER = "<!-- BEGIN_AUTOGEN_ENV_DOCS -->"
END_MARKER = "<!-- END_AUTOGEN_ENV_DOCS -->"


def _format_type(spec: EnvVarSpec) -> str:
    return spec.type.__name__


def _format_default(spec: EnvVarSpec) -> str:
    if spec.default is None:
        return "*(none)*"
    if spec.type is bool:
        return str(spec.default).lower()
    if spec.type is str and spec.default == "":
        return '`""`'
    return f"`{spec.default!r}`"


def _format_range(spec: EnvVarSpec) -> str:
    if spec.range is None:
        return ""
    lo, hi = spec.range
    return f" Range: {lo}–{hi}."


def build_table(registry: dict) -> str:
    """Return the Markdown table string (without surrounding markers)."""
    rows = []
    for name in sorted(registry):
        spec = registry[name]
        desc = spec.description.replace("|", "\\|")
        desc += _format_range(spec)
        row = f"| `{name}` | {spec.component} | {_format_type(spec)} " f"| {_format_default(spec)} | {desc} |"
        rows.append(row)

    header = "| Name | Component | Type | Default | Description |\n" "|---|---|---|---|---|"
    table_body = "\n".join(rows)
    count_note = f"\n\n*{len(registry)} variables registered as of last generation.*\n"
    return f"{header}\n{table_body}{count_note}"


def rewrite_docs(docs_path: Path, table: str) -> None:
    """Replace the autogenerated section in *docs_path* with *table*."""
    original = docs_path.read_text(encoding="utf-8")

    begin_idx = original.find(BEGIN_MARKER)
    end_idx = original.find(END_MARKER)

    if begin_idx == -1 or end_idx == -1:
        raise ValueError(
            f"Magic markers not found in {docs_path}. "
            f"Add '<!-- BEGIN_AUTOGEN_ENV_DOCS -->' and '<!-- END_AUTOGEN_ENV_DOCS -->'."
        )
    if begin_idx >= end_idx:
        raise ValueError("BEGIN marker must appear before END marker.")

    new_content = original[: begin_idx + len(BEGIN_MARKER)] + "\n" + table + original[end_idx:]
    docs_path.write_text(new_content, encoding="utf-8")


def main() -> int:
    if not DOCS_PATH.exists():
        print(f"ERROR: {DOCS_PATH} not found.", file=sys.stderr)
        return 1

    if not REGISTRY:
        print("ERROR: REGISTRY is empty — nothing to generate.", file=sys.stderr)
        return 1

    table = build_table(REGISTRY)
    try:
        rewrite_docs(DOCS_PATH, table)
    except ValueError as exc:
        print(f"ERROR: {exc}", file=sys.stderr)
        return 1

    print(f"Generated env-var docs for {len(REGISTRY)} variables into {DOCS_PATH}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
