# Copyright 2025-2026 mrveiss
# SPDX-License-Identifier: Apache-2.0
# AutoBot - AI-Powered Automation Platform
# Author: mrveiss
"""
Gmail Service for Operator Dashboard (MVA-2894).

Handles Gmail API integration for sending email replies from triaged threads.
Uses OAuth 2.0 credentials generated by scripts/gmail_authorize.py.
"""

import base64
import os
from email.mime.text import MIMEText
from pathlib import Path
from typing import Any, Dict

from google.auth.transport.requests import Request
from google.oauth2.credentials import Credentials
from googleapiclient.discovery import build
from googleapiclient.errors import HttpError

from autobot_shared.logging_manager import get_logger

logger = get_logger(__name__)


class GmailService:
    """Gmail API service for sending emails."""

    # Gmail API scopes
    SCOPES = [
        "https://www.googleapis.com/auth/gmail.readonly",
        "https://www.googleapis.com/auth/gmail.send",
    ]

    def __init__(
        self,
        token_path: str | Path | None = None,
        credentials_path: str | Path | None = None,
    ):
        """
        Initialize Gmail service.

        Args:
            token_path: Path to gmail_token.json (default: project root)
            credentials_path: Path to credentials.json (default: project root)

        Raises:
            FileNotFoundError: If token file not found
            ValueError: If credentials are invalid or expired
        """
        # Default paths relative to project root
        project_root = Path(__file__).parent.parent.parent
        self.token_path = Path(token_path or os.getenv("GMAIL_TOKEN_PATH") or (project_root / "gmail_token.json"))
        self.credentials_path = Path(
            credentials_path or os.getenv("GMAIL_CREDENTIALS_PATH") or (project_root / "credentials.json")
        )

        self._credentials: Credentials | None = None
        self._service = None

    def _load_credentials(self) -> Credentials:
        """
        Load and validate Gmail OAuth credentials.

        Returns:
            Valid Credentials object

        Raises:
            FileNotFoundError: If token file not found
            ValueError: If credentials are invalid or cannot be refreshed
        """
        if not self.token_path.exists():
            raise FileNotFoundError(
                f"Gmail token not found: {self.token_path}\n" f"Run: python scripts/gmail_authorize.py"
            )

        creds = Credentials.from_authorized_user_file(str(self.token_path), self.SCOPES)

        # Refresh if expired
        if creds.expired and creds.refresh_token:
            logger.info("Refreshing expired Gmail token")
            try:
                creds.refresh(Request())
                # Save refreshed token
                self.token_path.write_text(creds.to_json())
            except Exception as e:
                raise ValueError(
                    f"Failed to refresh Gmail token: {e}\n" f"Re-authorize: python scripts/gmail_authorize.py"
                )

        if not creds.valid:
            raise ValueError("Gmail credentials are invalid\nRe-authorize: python scripts/gmail_authorize.py")

        return creds

    def _get_service(self):
        """Get or create Gmail API service instance."""
        if self._service is None:
            if self._credentials is None:
                self._credentials = self._load_credentials()
            self._service = build("gmail", "v1", credentials=self._credentials)
        return self._service

    def send_reply(
        self,
        thread_id: str,
        to: str,
        subject: str,
        body: str,
        from_address: str = "me",
    ) -> Dict[str, Any]:
        """
        Send an email reply to a thread.

        Args:
            thread_id: Gmail thread ID to reply to
            to: Recipient email address
            subject: Email subject (should match thread for proper threading)
            body: Email body (plain text)
            from_address: Sender address (default: "me" = authenticated user)

        Returns:
            Dict containing sent message metadata:
                - id: Gmail message ID
                - threadId: Gmail thread ID
                - labelIds: Message labels

        Raises:
            FileNotFoundError: If Gmail token not found
            ValueError: If credentials invalid
            HttpError: If Gmail API request fails
        """
        try:
            service = self._get_service()

            # Create MIME message
            message = MIMEText(body)
            message["to"] = to
            message["from"] = from_address
            message["subject"] = subject

            # Encode as base64url
            encoded_message = base64.urlsafe_b64encode(message.as_bytes()).decode()

            # Send via Gmail API
            send_request = {
                "raw": encoded_message,
                "threadId": thread_id,  # Reply to existing thread
            }

            result = service.users().messages().send(userId="me", body=send_request).execute()

            logger.info(f"Sent email reply: message_id={result['id']}, " f"thread_id={thread_id}, to={to}")

            return result

        except HttpError as e:
            logger.error(f"Gmail API error sending reply: {e}")
            raise
        except Exception as e:
            logger.error(f"Unexpected error sending email: {e}")
            raise

    def send_message(
        self,
        to: str,
        subject: str,
        body: str,
        from_address: str = "me",
    ) -> Dict[str, Any]:
        """
        Send a new email message (not a reply).

        Args:
            to: Recipient email address
            subject: Email subject
            body: Email body (plain text)
            from_address: Sender address (default: "me" = authenticated user)

        Returns:
            Dict containing sent message metadata

        Raises:
            FileNotFoundError: If Gmail token not found
            ValueError: If credentials invalid
            HttpError: If Gmail API request fails
        """
        try:
            service = self._get_service()

            # Create MIME message
            message = MIMEText(body)
            message["to"] = to
            message["from"] = from_address
            message["subject"] = subject

            # Encode as base64url
            encoded_message = base64.urlsafe_b64encode(message.as_bytes()).decode()

            # Send via Gmail API
            result = service.users().messages().send(userId="me", body={"raw": encoded_message}).execute()

            logger.info(f"Sent new email: message_id={result['id']}, to={to}")

            return result

        except HttpError as e:
            logger.error(f"Gmail API error sending message: {e}")
            raise
        except Exception as e:
            logger.error(f"Unexpected error sending email: {e}")
            raise
