# Copyright 2025-2026 mrveiss
# SPDX-License-Identifier: Apache-2.0
# AutoBot - AI-Powered Automation Platform
# Author: mrveiss
"""
Ansible secrets mapping shared between setup_wizard and playbook_executor.

Single source of truth for the SLM secret key -> Ansible variable name
mapping (#3519).  Any caller that needs to inject stored secrets as Ansible
extra_vars should import _SECRET_TO_ANSIBLE_VAR and fetch_deploy_secrets
from here.
"""

import logging

logger = logging.getLogger(__name__)

# Maps SLM secrets-store keys to the Ansible extra_var names they become
# when injected into a playbook run.
#
# "hf_token"               -> tts_hf_token  (HuggingFace token for TTS worker)
# "autobot_internal_api_key" -> autobot_internal_api_key
#     Internal API key shared between SLM backend and main backend (#1779,
#     #3512).  Stored via the SLM secrets UI; injected as an Ansible extra_var
#     and rendered into slm-secrets.env and backend.env.
#
# NOTE (#10400): SLM_SECRET_KEY is NOT distributed here. It is not a SystemSecret
# DB row — it is generated by the slm_manager role into /etc/autobot/slm-secrets.env
# (and read by SLM config.py from env / the persisted keys file). The backend role
# reads SLM_SECRET_KEY from that file at deploy time and surfaces it as
# backend_jwt_secret so AUTOBOT_JWT_SECRET == SLM_SECRET_KEY (same #7689 pattern as
# SLM_AUTH_TOKEN). Adding it to this DB-keyed map would never resolve.
_SECRET_TO_ANSIBLE_VAR: dict[str, str] = {
    "hf_token": "tts_hf_token",  # nosec B105  # dict maps secret DB key names to Ansible variable names, not credential
    "autobot_internal_api_key": "autobot_internal_api_key",
}

# Maps a managed secret key to the role name(s) that can receive it via the
# lightweight "apply secrets" propagation path (#11719) — re-render just the
# role's env-file template + restart its systemd service, instead of a full
# role redeploy (venv rebuild, package installs, model predownload).
#
# Only secrets with a SINGLE clean env-template + service-restart consumer
# are listed here. "autobot_internal_api_key" is intentionally NOT included:
# it fans out across backend.env.j2 (autobot-backend), the slm_manager nginx
# conf template (autobot-slm.conf.j2), and slm_agent's systemd env file — no
# single clean env-template+restart target, so rotating it still requires the
# full role redeploy ("Migrate"/"Redeploy") path for now.
_SECRET_TO_DEPENDENT_ROLES: dict[str, list[str]] = {
    "hf_token": ["tts-worker"],
}


async def fetch_deploy_secrets() -> dict[str, str]:
    """Read stored SLM secrets and return them as Ansible extra_vars (#3519, #3778).

    Single source of truth used by setup_wizard, playbook_executor, and
    infrastructure — any deploy path that needs to inject stored secrets as
    Ansible extra_vars should call this function.

    Each key is resolved via ``system_secrets_vault.retrieve_secret``
    (#10088 Task 6a): legacy ``system_secrets`` first, unified System vault
    fallback. ``autobot_internal_api_key`` never reaches the vault path —
    it is the auth-bootstrap credential ``vault_client`` uses to reach the
    vault in the first place (confused-deputy guard; see
    ``system_secrets_vault`` module docstring), and its legacy row is never
    pruned, so the fallback is never exercised for it in practice.

    Returns an empty dict and logs a warning if the DB is unavailable — the
    deploy is allowed to proceed rather than being blocked by a secret-fetch
    failure.
    """
    from services.database import db_service
    from services.system_secrets_vault import retrieve_secret

    extra: dict[str, str] = {}
    try:
        async with db_service.session() as session:
            for key, ansible_var in _SECRET_TO_ANSIBLE_VAR.items():
                value = await retrieve_secret(session, key)
                if value:
                    extra[ansible_var] = value
    except Exception:
        logger.warning(
            "fetch_deploy_secrets: could not load SLM secrets — " "deploy will proceed without them (#3519)",
            exc_info=True,
        )
    return extra
