#!/bin/bash
# Copyright 2025-2026 mrveiss
# SPDX-License-Identifier: Apache-2.0
# Setup least-privilege passwordless sudo for AutoBot process-management operations
#
# #14317: this used to hardcode NOPASSWD sudo for a leftover 'kali' dev-image
# account (#926) -- a leftover on any host without that account (visudo accepts
# an unknown name silently, so the rule never applied), and a passwordless path
# to root on any host that DOES have one, via `usermod -aG docker`: docker group
# membership is equivalent to root, so that line was a privilege-escalation
# primitive sitting beside plain process-inspection commands.
#
# Fixed:
#  - the account is resolved via AUTOBOT_USER, the same override pattern
#    roles/vnc uses for its own account (VNC_USER/AUTOBOT_VNC_USER) -- default
#    'autobot', matching autobot_user in
#    autobot-slm-backend/ansible/roles/common/vars/main.yml. A host provisions
#    sudoers for the account it actually runs as, never a name that isn't this
#    platform's own.
#  - `usermod -aG docker` is gone. Docker group membership is granted once, at
#    account-provisioning time (see install-bare-metal.sh's `useradd`), or
#    interactively with a real sudo password prompt (run_agent.sh,
#    setup/setup_repair.sh) -- never passwordlessly at runtime. Group
#    membership is a standing grant, not a repeated operational need, so it
#    does not belong in this file.
#  - the remaining three commands are exactly what the platform's own
#    automation invokes without further privilege: `sudo lsof` / `sudo kill`
#    for port cleanup (run_agent.sh, deployment/deploy_hybrid.sh,
#    ansible/fix-backend-deadlock.sh) and `sudo pkill` for process cleanup
#    (run_agent.sh).

set -euo pipefail

AUTOBOT_USER="${AUTOBOT_USER:-autobot}"
SUDOERS_FILE="/etc/sudoers.d/autobot"

echo "Setting up passwordless sudo for AutoBot operations (user: ${AUTOBOT_USER})..."

sudoers_tmp="$(mktemp)"
trap 'rm -f "${sudoers_tmp}"' EXIT

# Scoped to the exact binaries AutoBot's own tooling invokes for port/process
# diagnostics -- no wildcard args, no privilege-escalation primitives.
cat > "${sudoers_tmp}" <<EOF
# AutoBot passwordless sudo -- process-management commands only (#14317).
# Generated by setup/system/setup_passwordless_sudo.sh. Do not hand-edit;
# re-run the script (with AUTOBOT_USER set, if not 'autobot') instead.
${AUTOBOT_USER} ALL=(ALL) NOPASSWD: /usr/bin/lsof
${AUTOBOT_USER} ALL=(ALL) NOPASSWD: /usr/bin/kill
${AUTOBOT_USER} ALL=(ALL) NOPASSWD: /usr/bin/pkill
EOF

# Validate BEFORE the file is live -- unlike writing straight to
# /etc/sudoers.d and validating after, an invalid rule set is never installed.
if sudo visudo -c -f "${sudoers_tmp}"; then
    sudo install -m 0440 -o root -g root "${sudoers_tmp}" "${SUDOERS_FILE}"
    echo "✅ Passwordless sudo configured successfully for AutoBot operations"
    echo "The following commands now work without password for ${AUTOBOT_USER}:"
    echo "  - sudo lsof (port checking)"
    echo "  - sudo kill (process termination)"
    echo "  - sudo pkill (process cleanup)"
else
    echo "❌ Failed to configure sudoers file (visudo validation failed)"
    exit 1
fi
