#!/usr/bin/env bash
# Copyright 2025-2026 mrveiss
# SPDX-License-Identifier: Apache-2.0
# AutoBot - AI-Powered Automation Platform
# Author: mrveiss
#
# install-git-hooks.sh — install AutoBot's git hooks as REAL files (copied),
# never as symlinks into a worktree.
# ============================================================================
#
# Why this exists (Issue #11598):
#   The old tools/git-hooks/install_hooks.sh symlinked each hook into
#   .git/hooks/ pointing at a *worktree* path. When that worktree was deleted
#   the symlink dangled and the hook silently stopped running. On top of that
#   core.hooksPath had been pinned to a machine-specific absolute path, which
#   is neither portable nor the git default.
#
# What this installer guarantees:
#   * Real copied hook files (self-contained) — survive worktree deletion.
#   * Portable — repo root and hooks dir are derived from git, never hardcoded.
#   * core.hooksPath normalised back to git's default (repo .git/hooks) when it
#     was pinned to a foreign/absolute path.
#   * Dangling symlinks in the hooks dir are detected, reported, and replaced.
#   * Idempotent — safe to re-run; a second run is a no-op when up to date.
#
# Usage:
#   bash scripts/install-git-hooks.sh          # install/refresh hooks
#   HOOKS_DEST=/tmp/x bash scripts/install-git-hooks.sh   # override dest (tests)
#
# Related: #4113 (branch guard), #11581, #11593.

set -uo pipefail

RED='\033[0;31m'; YELLOW='\033[1;33m'; GREEN='\033[0;32m'; CYAN='\033[0;36m'; NC='\033[0m'
info()  { printf "${CYAN}[install-hooks]${NC} %s\n" "$*"; }
ok()    { printf "${GREEN}[install-hooks]${NC} %s\n" "$*"; }
warn()  { printf "${YELLOW}[install-hooks WARN]${NC} %s\n" "$*" >&2; }
fail()  { printf "${RED}[install-hooks FAIL]${NC} %s\n" "$*" >&2; }

# Hooks this installer manages. Each name must exist as a real file under
# tools/git-hooks/<name>.
MANAGED_HOOKS="pre-commit pre-push"

# --- Locate the repo and its canonical hook templates (portable) -----------
REPO_ROOT="$(git rev-parse --show-toplevel 2>/dev/null || echo "")"
if [ -z "$REPO_ROOT" ]; then
    fail "not inside a git repository"
    exit 1
fi
HOOKS_SRC="$REPO_ROOT/tools/git-hooks"
if [ ! -d "$HOOKS_SRC" ]; then
    fail "hook template directory missing: $HOOKS_SRC"
    exit 1
fi

# --- Resolve the hooks destination (worktree-aware, absolute) --------------
# --git-common-dir points at the MAIN repo's .git even from inside a worktree,
# so hooks land in the shared hooks dir rather than a per-worktree one.
resolve_hooks_dest() {
    if [ -n "${HOOKS_DEST:-}" ]; then
        printf '%s\n' "$HOOKS_DEST"
        return
    fi
    local common_dir
    common_dir="$(git rev-parse --git-common-dir 2>/dev/null || echo "")"
    case "$common_dir" in
        /*) printf '%s/hooks\n' "$common_dir" ;;
        *)  printf '%s/hooks\n' "$(cd "$common_dir" && pwd)" ;;
    esac
}
HOOKS_DEST="$(resolve_hooks_dest)"

# --- Normalise core.hooksPath ----------------------------------------------
# If it is pinned to anything other than the resolved default hooks dir (e.g.
# an absolute machine-specific path — the #11598 bug), unset it so git falls
# back to its default. We only touch the LOCAL repo config, never global.
normalise_hooks_path() {
    local configured
    configured="$(git config --local --get core.hooksPath 2>/dev/null || echo "")"
    [ -z "$configured" ] && return 0

    local resolved="$configured"
    case "$configured" in
        /*) : ;;
        *)  resolved="$REPO_ROOT/$configured" ;;
    esac
    if [ "$resolved" = "$HOOKS_DEST" ]; then
        return 0
    fi
    warn "core.hooksPath was pinned to a non-default path: $configured"
    warn "  unsetting it so git uses the default hooks dir: $HOOKS_DEST"
    git config --local --unset core.hooksPath 2>/dev/null || true
}

# --- Replace one hook with the real template file --------------------------
# Detects and clears dangling/foreign symlinks, backs up unmanaged regular
# files, and copies the template verbatim. Idempotent by content.
install_one_hook() {
    local name="$1"
    local src="$HOOKS_SRC/$name"
    local dest="$HOOKS_DEST/$name"

    if [ ! -f "$src" ]; then
        warn "template missing, skipping: $src"
        return 0
    fi

    # Never clobber a pre-commit-FRAMEWORK-managed hook. When `pre-commit
    # install` has written .git/hooks/<name>, that hook already runs the FULL
    # quality suite (black/flake8/mypy/function-length/... AND target-branch-
    # guard). Our standalone is only a FALLBACK for when the `pre-commit`
    # binary isn't installed, so leave the framework hook in place (#11598).
    if [ -f "$dest" ] && [ ! -L "$dest" ] \
        && grep -q "generated by pre-commit" "$dest" 2>/dev/null; then
        warn "$name is managed by the pre-commit framework — leaving it in place"
        warn "  (it already runs target-branch-guard + the full quality suite)"
        return 0
    fi

    if [ -L "$dest" ]; then
        local target; target="$(readlink "$dest" 2>/dev/null || echo "")"
        if [ ! -e "$dest" ]; then
            warn "removing DANGLING symlink: $name -> $target"
        else
            warn "removing symlink (installing a real file instead): $name -> $target"
        fi
        rm -f "$dest"
    elif [ -f "$dest" ]; then
        if cmp -s "$src" "$dest"; then
            chmod +x "$dest" || { fail "failed to chmod +x $dest"; return 1; }
            ok "$name already up to date"
            return 0
        fi
        if ! grep -q "AutoBot" "$dest" 2>/dev/null; then
            local backup="$dest.bak.$(date +%Y%m%d-%H%M%S)"
            mv "$dest" "$backup"
            warn "backed up existing unmanaged $name -> $(basename "$backup")"
        fi
    fi

    cp "$src" "$dest" || { fail "failed to copy $name into $dest"; return 1; }
    chmod +x "$dest" || { fail "failed to chmod +x $dest"; return 1; }
    ok "installed $name"
}

main() {
    info "repo root:   $REPO_ROOT"
    info "hooks dest:  $HOOKS_DEST"
    mkdir -p "$HOOKS_DEST"
    normalise_hooks_path
    local rc=0
    for hook in $MANAGED_HOOKS; do
        install_one_hook "$hook" || rc=1
    done
    echo ""
    if [ "$rc" -ne 0 ]; then
        fail "one or more hooks failed to install"
        return 1
    fi
    ok "done. Bypass a hook only when you must: git commit/push --no-verify"
}

main "$@"
