# Copyright 2025-2026 mrveiss
# SPDX-License-Identifier: Apache-2.0
---
# Common role handlers

- name: reload firewall
  ufw:
    state: reloaded
  become: true

- name: restart ssh
  systemd:
    name: sshd
    state: restarted
  become: true
