# Copyright 2025-2026 mrveiss
# SPDX-License-Identifier: Apache-2.0
# AutoBot - AI-Powered Automation Platform
# Author: mrveiss
#
# Ansible Monitoring Role - Handlers
---

- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true

- name: Restart prometheus
  ansible.builtin.systemd:
    name: prometheus
    state: restarted

- name: Restart grafana
  ansible.builtin.systemd:
    name: grafana-server
    state: restarted

- name: Restart node_exporter
  ansible.builtin.systemd:
    name: node_exporter
    state: restarted
