source "https://rubygems.org"

gem "jekyll", "~> 4.3"
gem "just-the-docs", "~> 0.10"
gem "jekyll-seo-tag"

# Windows / tzinfo
gem "tzinfo-data", platforms: %i[windows jruby]
gem "wdm", ">= 0.1.0", platforms: %i[windows]
