RISKY_COMMAND_PATTERNS = [
    "rm -r",
    "rm -r",
    "sudo rm",
    "rmdir",
    "dd if=",
    "mkfs",
    "fdisk",
    "parted",
    "chmod 777",
    "chmod -R 777",
    "chown -R",
    "> /dev/",
    "/dev/sda",
    "/dev/sdb",
    "iptables -F",
    "ufw disable",
    "shutdown",
    "reboot",
    "halt",
    "powerof",
    "apt-get remove",
    "yum remove",
    "rm /etc/",
]

MODERATE_RISK_PATTERNS = [
    "sudo",
    "su -",
    "chmod",
    "chown",
    "apt-get install",
    "yum install",
    "pip install",
    "systemctl",
    "service",
    "mount",
    "umount",
]
