# AutoBot - AI-Powered Automation Platform
# Copyright (c) 2026 mrveiss
# Author: mrveiss
"""Knowledge base API response schemas."""

from knowledge.schemas.documents import (
    DocsBrowseResponse,
    DocsCategoriesResponse,
    DocsCategoryEntry,
    DocsFiltersApplied,
    DocsPagination,
    DocsStatsEnvelope,
    DocsStatsResponse,
    DocsWatcherControlResponse,
    DocsWatcherStatusResponse,
)
from knowledge.schemas.facts import (
    AddFactResponse,
    AddTextResponse,
    AddUrlResponse,
    AudioIngestResponse,
    ClearAllResponse,
    FactByCategoryEntry,
    FactByKeyResponse,
    FactsByCategoryResponse,
    KnowledgeEntriesResponse,
    KnowledgeEntry,
    ManPageSearchResponse,
    QueryKnowledgeResponse,
    UploadFileResponse,
)
from knowledge.schemas.operations import (
    ImportStatisticsResponse,
    ImportStatusResponse,
    KnowledgeHealthResponse,
    KnowledgeStatsResponse,
    MachineKnowledgeInitComponents,
    MachineKnowledgeInitResponse,
    MachineProfileCapabilities,
    MachineProfileResponse,
    ManPagesIntegrateResponse,
    ManPagesSummaryEnvelope,
    ManPagesSummaryResponse,
    OrgKnowledgeConfigResponse,
    TestCategoriesResponse,
)
from knowledge.schemas.search import (
    EnhancedSearchResponse,
    EnhancedSearchV2Response,
    ExpandQueryResponse,
    KnowledgeSearchResponse,
    RagSearchResponse,
    RecordClickResponse,
    SearchAnalyticsResponse,
    SimilaritySearchResponse,
)
from knowledge.schemas.rag import (
    AdvancedSearchResponse,
    BenchmarkRunResponse,
    EntityHistoryResponse,
    LoopApproveResponse,
    LoopRejectResponse,
    LoopStatusResponse,
    RagConfigResponse,
    RagStatsResponse,
    RerankResultsResponse,
    UpdateRagConfigResponse,
)
from knowledge.schemas.stats import (
    DetailedKnowledgeSizeMetrics,
    DetailedKnowledgeStats,
    KnowledgeBasicStatsEnvelope,
    KnowledgeCategoriesResponse,
    KnowledgeCategoryEntry,
    KnowledgeMainCategoriesResponse,
    KnowledgeMainCategoryEntry,
    KnowledgeStatsBasic,
)

__all__ = [
    # stats.py (pre-existing)
    "DetailedKnowledgeSizeMetrics",
    "DetailedKnowledgeStats",
    "KnowledgeBasicStatsEnvelope",
    "KnowledgeCategoriesResponse",
    "KnowledgeCategoryEntry",
    "KnowledgeMainCategoriesResponse",
    "KnowledgeMainCategoryEntry",
    "KnowledgeStatsBasic",
    # facts.py
    "AddFactResponse",
    "AddTextResponse",
    "AddUrlResponse",
    "AudioIngestResponse",
    "ClearAllResponse",
    "FactByCategoryEntry",
    "FactByKeyResponse",
    "FactsByCategoryResponse",
    "KnowledgeEntriesResponse",
    "KnowledgeEntry",
    "ManPageSearchResponse",
    "QueryKnowledgeResponse",
    "UploadFileResponse",
    # documents.py
    "DocsBrowseResponse",
    "DocsCategoriesResponse",
    "DocsCategoryEntry",
    "DocsFiltersApplied",
    "DocsPagination",
    "DocsStatsEnvelope",
    "DocsStatsResponse",
    "DocsWatcherControlResponse",
    "DocsWatcherStatusResponse",
    # rag.py
    "AdvancedSearchResponse",
    "BenchmarkRunResponse",
    "EntityHistoryResponse",
    "LoopApproveResponse",
    "LoopRejectResponse",
    "LoopStatusResponse",
    "RagConfigResponse",
    "RagStatsResponse",
    "RerankResultsResponse",
    "UpdateRagConfigResponse",
    # search.py
    "EnhancedSearchResponse",
    "EnhancedSearchV2Response",
    "ExpandQueryResponse",
    "KnowledgeSearchResponse",
    "RagSearchResponse",
    "RecordClickResponse",
    "SearchAnalyticsResponse",
    "SimilaritySearchResponse",
    # operations.py
    "ImportStatisticsResponse",
    "ImportStatusResponse",
    "KnowledgeHealthResponse",
    "KnowledgeStatsResponse",
    "MachineKnowledgeInitComponents",
    "MachineKnowledgeInitResponse",
    "MachineProfileCapabilities",
    "MachineProfileResponse",
    "ManPagesIntegrateResponse",
    "ManPagesSummaryEnvelope",
    "ManPagesSummaryResponse",
    "OrgKnowledgeConfigResponse",
    "TestCategoriesResponse",
]
