# Copyright 2025-2026 mrveiss
# SPDX-License-Identifier: Apache-2.0
# AutoBot - AI-Powered Automation Platform
# Copyright (c) 2025 mrveiss
# Author: mrveiss
---
# Docker role handlers (#3424)

- name: restart docker
  ansible.builtin.systemd:
    name: docker
    state: restarted
    daemon_reload: true
